In [2]:
import numpy as ny

In [15]:
a=ny.array([(1,2,3),(4,5,6)])

In [16]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
trans=ny.transpose(a)

In [8]:
print(trans)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print(trans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
trans.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [17]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
zer=ny.zeros((3,3))

In [24]:
print(zer)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
one=ny.ones((3,3))

In [26]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
ny.random.random((2,2))

array([[0.25418498, 0.53832618],
       [0.06585323, 0.92952624]])